export {default as Header} from './Header';
export {default as SearchBar} from './SearchBar';
export {default as Hero} from './Hero'
export {default as Slider} from './Slider'
export {default as GamesList} from './GamesList'
export {default as GameCard} from './GameCard'
export {default as Footer} from './Footer'
export {default as ProfileInfo} from './ProfileInfo'
export {default as ReviewsList} from './ReviewsList'
export {default as EditProfile} from './EditProfile'